# Generated by Django 3.0.3 on 2020-08-15 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('technicalcourses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='il',
            new_name='ct',
        ),
        migrations.RemoveField(
            model_name='details',
            name='sp',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='startFrom',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 15, 35, 53, 179427, tzinfo=utc), verbose_name='start from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='choice',
            field=models.BooleanField(default=False),
        ),
    ]
