# Generated by Django 3.0.3 on 2020-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalcourses', '0002_auto_20200815_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='startFrom',
            field=models.DateTimeField(verbose_name='start from'),
        ),
    ]
