# Generated by Django 3.0.3 on 2020-08-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalcourses', '0003_auto_20200815_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='startFrom',
        ),
    ]
